/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoltaDosCdsRouteImport } from './routes/volta-dos-cds'
import { Route as TiktokViagensRouteImport } from './routes/tiktok-viagens'
import { Route as RobosDomesticosRouteImport } from './routes/robos-domesticos'
import { Route as ReportagemLosharikRouteImport } from './routes/reportagem-losharik'
import { Route as GptVsGeminiRouteImport } from './routes/gpt-vs-gemini'
import { Route as DuasLuasHaven1RouteImport } from './routes/duas-luas-haven1'
import { Route as AneisInteligentesRouteImport } from './routes/aneis-inteligentes'
import { Route as AlertaDeepfakeBrasilRouteImport } from './routes/alerta-deepfake-brasil'
import { Route as IndexRouteImport } from './routes/index'

const VoltaDosCdsRoute = VoltaDosCdsRouteImport.update({
  id: '/volta-dos-cds',
  path: '/volta-dos-cds',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokViagensRoute = TiktokViagensRouteImport.update({
  id: '/tiktok-viagens',
  path: '/tiktok-viagens',
  getParentRoute: () => rootRouteImport,
} as any)
const RobosDomesticosRoute = RobosDomesticosRouteImport.update({
  id: '/robos-domesticos',
  path: '/robos-domesticos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportagemLosharikRoute = ReportagemLosharikRouteImport.update({
  id: '/reportagem-losharik',
  path: '/reportagem-losharik',
  getParentRoute: () => rootRouteImport,
} as any)
const GptVsGeminiRoute = GptVsGeminiRouteImport.update({
  id: '/gpt-vs-gemini',
  path: '/gpt-vs-gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasLuasHaven1Route = DuasLuasHaven1RouteImport.update({
  id: '/duas-luas-haven1',
  path: '/duas-luas-haven1',
  getParentRoute: () => rootRouteImport,
} as any)
const AneisInteligentesRoute = AneisInteligentesRouteImport.update({
  id: '/aneis-inteligentes',
  path: '/aneis-inteligentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertaDeepfakeBrasilRoute = AlertaDeepfakeBrasilRouteImport.update({
  id: '/alerta-deepfake-brasil',
  path: '/alerta-deepfake-brasil',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerta-deepfake-brasil': typeof AlertaDeepfakeBrasilRoute
  '/aneis-inteligentes': typeof AneisInteligentesRoute
  '/duas-luas-haven1': typeof DuasLuasHaven1Route
  '/gpt-vs-gemini': typeof GptVsGeminiRoute
  '/reportagem-losharik': typeof ReportagemLosharikRoute
  '/robos-domesticos': typeof RobosDomesticosRoute
  '/tiktok-viagens': typeof TiktokViagensRoute
  '/volta-dos-cds': typeof VoltaDosCdsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerta-deepfake-brasil': typeof AlertaDeepfakeBrasilRoute
  '/aneis-inteligentes': typeof AneisInteligentesRoute
  '/duas-luas-haven1': typeof DuasLuasHaven1Route
  '/gpt-vs-gemini': typeof GptVsGeminiRoute
  '/reportagem-losharik': typeof ReportagemLosharikRoute
  '/robos-domesticos': typeof RobosDomesticosRoute
  '/tiktok-viagens': typeof TiktokViagensRoute
  '/volta-dos-cds': typeof VoltaDosCdsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerta-deepfake-brasil': typeof AlertaDeepfakeBrasilRoute
  '/aneis-inteligentes': typeof AneisInteligentesRoute
  '/duas-luas-haven1': typeof DuasLuasHaven1Route
  '/gpt-vs-gemini': typeof GptVsGeminiRoute
  '/reportagem-losharik': typeof ReportagemLosharikRoute
  '/robos-domesticos': typeof RobosDomesticosRoute
  '/tiktok-viagens': typeof TiktokViagensRoute
  '/volta-dos-cds': typeof VoltaDosCdsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerta-deepfake-brasil'
    | '/aneis-inteligentes'
    | '/duas-luas-haven1'
    | '/gpt-vs-gemini'
    | '/reportagem-losharik'
    | '/robos-domesticos'
    | '/tiktok-viagens'
    | '/volta-dos-cds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerta-deepfake-brasil'
    | '/aneis-inteligentes'
    | '/duas-luas-haven1'
    | '/gpt-vs-gemini'
    | '/reportagem-losharik'
    | '/robos-domesticos'
    | '/tiktok-viagens'
    | '/volta-dos-cds'
  id:
    | '__root__'
    | '/'
    | '/alerta-deepfake-brasil'
    | '/aneis-inteligentes'
    | '/duas-luas-haven1'
    | '/gpt-vs-gemini'
    | '/reportagem-losharik'
    | '/robos-domesticos'
    | '/tiktok-viagens'
    | '/volta-dos-cds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertaDeepfakeBrasilRoute: typeof AlertaDeepfakeBrasilRoute
  AneisInteligentesRoute: typeof AneisInteligentesRoute
  DuasLuasHaven1Route: typeof DuasLuasHaven1Route
  GptVsGeminiRoute: typeof GptVsGeminiRoute
  ReportagemLosharikRoute: typeof ReportagemLosharikRoute
  RobosDomesticosRoute: typeof RobosDomesticosRoute
  TiktokViagensRoute: typeof TiktokViagensRoute
  VoltaDosCdsRoute: typeof VoltaDosCdsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volta-dos-cds': {
      id: '/volta-dos-cds'
      path: '/volta-dos-cds'
      fullPath: '/volta-dos-cds'
      preLoaderRoute: typeof VoltaDosCdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok-viagens': {
      id: '/tiktok-viagens'
      path: '/tiktok-viagens'
      fullPath: '/tiktok-viagens'
      preLoaderRoute: typeof TiktokViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robos-domesticos': {
      id: '/robos-domesticos'
      path: '/robos-domesticos'
      fullPath: '/robos-domesticos'
      preLoaderRoute: typeof RobosDomesticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportagem-losharik': {
      id: '/reportagem-losharik'
      path: '/reportagem-losharik'
      fullPath: '/reportagem-losharik'
      preLoaderRoute: typeof ReportagemLosharikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpt-vs-gemini': {
      id: '/gpt-vs-gemini'
      path: '/gpt-vs-gemini'
      fullPath: '/gpt-vs-gemini'
      preLoaderRoute: typeof GptVsGeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas-luas-haven1': {
      id: '/duas-luas-haven1'
      path: '/duas-luas-haven1'
      fullPath: '/duas-luas-haven1'
      preLoaderRoute: typeof DuasLuasHaven1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aneis-inteligentes': {
      id: '/aneis-inteligentes'
      path: '/aneis-inteligentes'
      fullPath: '/aneis-inteligentes'
      preLoaderRoute: typeof AneisInteligentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerta-deepfake-brasil': {
      id: '/alerta-deepfake-brasil'
      path: '/alerta-deepfake-brasil'
      fullPath: '/alerta-deepfake-brasil'
      preLoaderRoute: typeof AlertaDeepfakeBrasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertaDeepfakeBrasilRoute: AlertaDeepfakeBrasilRoute,
  AneisInteligentesRoute: AneisInteligentesRoute,
  DuasLuasHaven1Route: DuasLuasHaven1Route,
  GptVsGeminiRoute: GptVsGeminiRoute,
  ReportagemLosharikRoute: ReportagemLosharikRoute,
  RobosDomesticosRoute: RobosDomesticosRoute,
  TiktokViagensRoute: TiktokViagensRoute,
  VoltaDosCdsRoute: VoltaDosCdsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
